services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    volumes:
      - ./app:/app
    working_dir: /app
    command: pytest